'use client';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useApp } from './providers';
import { SiteHeader } from './site-header';
export function CartPage(){
 const {cart,subtotal,setQuantity,removeFromCart}=useApp(); const delivery=subtotal>=5000||!subtotal?0:250; const total=subtotal+delivery;
 return <main><SiteHeader/><div className="page-shell inner-page"><Link href="/menu" className="back-link"><ArrowLeft/> Continue shopping</Link><div className="page-title"><span className="section-kicker">YOUR BAG</span><h1>Your timepieces.</h1><p>{cart.length?`${cart.reduce((a,x)=>a+x.quantity,0)} item(s) selected.`:'Your bag is ready for something good.'}</p></div>{!cart.length?<div className="empty-state"><div className="empty-symbol"><ShoppingBag/></div><h2>Your bag is empty.</h2><p>Explore the latest WOOWWatches collection.</p><Link href="/menu" className="primary-button">Shop watches <ArrowRight/></Link></div>:<div className="cart-layout"><div className="cart-items">{cart.map(item=><article className="cart-item" key={item.id}><img src={item.image} alt={item.name}/><div><span>{item.gender}</span><h3>{item.name}</h3><b>Rs. {item.price.toLocaleString()}</b><div className="quantity"><button onClick={()=>setQuantity(item.id,item.quantity-1)}><Minus/></button><strong>{item.quantity}</strong><button onClick={()=>setQuantity(item.id,item.quantity+1)}><Plus/></button></div></div><button className="remove-button" onClick={()=>removeFromCart(item.id)}><Trash2/></button></article>)}</div><aside className="summary-card"><span className="section-kicker">ORDER SUMMARY</span><h2>Almost yours.</h2><div><span>Subtotal</span><b>Rs. {subtotal.toLocaleString()}</b></div><div><span>Delivery</span><b>{delivery?'Rs. 250':'FREE'}</b></div><small>Free delivery on orders of Rs. 5,000 or more.</small><hr/><div className="total-row"><span>Total</span><b>Rs. {total.toLocaleString()}</b></div><Link href="/checkout" className="primary-button">Checkout <ArrowRight/></Link></aside></div>}</div></main>;
}
