'use client';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, MapPin, ShieldCheck, ShoppingBag } from 'lucide-react';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useApp } from './providers';
export function CheckoutPage(){
 const {cart,subtotal,clearCart,saveOrder}=useApp(); const router=useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState({name:'',phone:'',address:'',note:''}); const delivery=subtotal>=5000?0:250; const total=subtotal+delivery;
 async function placeOrder(){setError('');if(!form.name.trim()||!form.phone.trim()||!form.address.trim()||!cart.length){setError('Please complete your name, phone and delivery address.');return}setLoading(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:form,items:cart.map(({id,quantity})=>({id,quantity})),payment:'cod'})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message);saveOrder({...d.order,items:cart});clearCart();router.push(`/orders?success=${d.order.id}`)}catch(e){setError(e instanceof Error?e.message:'Unable to place order.')}finally{setLoading(false)}}
 if(!cart.length)return <main><div className="checkout-empty"><ShoppingBag/><h1>Your bag is empty.</h1><Link href="/menu" className="primary-button">Shop collection</Link></div></main>;
 return <main><div className="checkout-top"><Link href="/cart" className="back-link"><ArrowLeft/> Back to bag</Link><Link href="/" className="checkout-brand"><img src="/logo.svg" alt="WOOWWatches"/><b>WOOW<span>Watches</span></b></Link><span><ShieldCheck/> Secure checkout</span></div><div className="checkout-page"><div className="checkout-main"><div className="checkout-heading"><span className="section-kicker">CHECKOUT / LOCAL DELIVERY</span><h1>Let’s make it yours.</h1><p>Complete your details. Cash on delivery is currently available.</p></div><section className="checkout-card"><div className="card-title"><MapPin/><div><h2>Delivery details</h2><p>Use a complete address so your order can reach you.</p></div></div><div className="form-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Phone number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="03xx xxxxxxx"/></label><label className="full">Delivery address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House, street, area, city"/></label><label className="full">Delivery note <small>optional</small><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Landmark or rider instructions"/></label></div></section><section className="checkout-card"><div className="card-title"><span className="payment-icon">₨</span><div><h2>Payment</h2><p>Simple and familiar.</p></div></div><div className="payment-option selected"><div><b>Cash on delivery</b><small>Pay when your order arrives.</small></div><Check/></div></section>{error&&<div className="error-box">{error}</div>}<button className="primary-button place-order" disabled={loading} onClick={placeOrder}>{loading?'Placing your order…':<>Place order · Rs. {total.toLocaleString()} <ArrowRight/></>}</button></div><aside className="checkout-summary"><span className="section-kicker">YOUR ORDER</span><h2>Order summary.</h2>{cart.map(i=><div className="mini-line" key={i.id}><img src={i.image} alt={i.name}/><div><b>{i.quantity}× {i.name}</b><span>Rs. {(i.price*i.quantity).toLocaleString()}</span></div></div>)}<hr/><div><span>Subtotal</span><b>Rs. {subtotal.toLocaleString()}</b></div><div><span>Delivery</span><b>{delivery?'Rs. 250':'FREE'}</b></div><div className="total-row"><span>Total</span><b>Rs. {total.toLocaleString()}</b></div></aside></div></main>;
}
